# Generated by Django 2.1.2 on 2018-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('weight_and_unit', models.CharField(max_length=64, verbose_name='weight_and_unit')),
                ('count', models.IntegerField(verbose_name='count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='price')),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(default=0, unique=True, verbose_name='check_id')),
                ('expected_date', models.DateField()),
                ('id_goods', models.ManyToManyField(to='shop.Good')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
