# Generated by Django 2.1.2 on 2018-10-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.IntegerField(default=0, unique=True, verbose_name='check_id')),
                ('expected_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='shop.User')),
            ],
        ),
        migrations.CreateModel(
            name='Good_item_in_bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='shop.Bill')),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good', to='shop.Good')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_goods',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
