# Generated by Django 2.1.2 on 2018-10-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181024_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good_item_in_bill',
            old_name='bill_id',
            new_name='bill',
        ),
        migrations.RenameField(
            model_name='good_item_in_bill',
            old_name='good_id',
            new_name='good',
        ),
        migrations.AddField(
            model_name='bill',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10000000),
        ),
    ]
