# Generated by Django 2.1.2 on 2018-10-25 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181025_0707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bill',
            new_name='id_bill',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='good',
            new_name='id_good',
        ),
    ]
