# Generated by Django 2.1.2 on 2018-10-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181025_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delete_from_shop',
            field=models.BooleanField(default=False),
        ),
    ]
