# Generated by Django 2.1.2 on 2018-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181101_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='expected_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=1000000, verbose_name='count'),
        ),
    ]
