# Generated by Django 2.1.2 on 2018-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20181105_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='good',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
